#!/usr/bin/env bash
# Alias definitions.

case "${__DOTFILES_OS_PLATFORM}" in
  ubuntu)
    alias fopen='xdg-open'

    alias tcopy='xclip -selection clipboard'
    alias tpaste='xclip -selection clipboard -o'

    todotxt_executable="todo-txt"
    ;;

  wsl-ubuntu)
    alias fopen='wslview'

    alias tcopy='clip.exe'

    todotxt_executable="todo-txt"
    ;;

  fedora)
    alias fopen='xdg-open'

    alias tcopy='xclip -selection clipboard'
    alias tpaste='xclip -selection clipboard -o'

    todotxt_executable="todo.sh"

    # https://sophieau.com/article/how-to-get-the-system-clipboard-working-in-vim-on-fedora/
    # https://vi.stackexchange.com/a/2065 # How do I get +clipboard support in Fedora 20?
    alias vim='vimx'
    export EDITOR="vimx"
    export VISUAL="$EDITOR"
    ;;


  macos)
    alias fopen='open'

    alias tcopy='pbcopy'
    alias tpaste='pbpaste'

    todotxt_executable="todo.sh"
    ;;
esac

alias todo="${todotxt_executable}"
alias todoadd="${todotxt_executable} -t add"
alias tododo="${todotxt_executable} -a do"
alias todoxp="${todotxt_executable} xp -o 10"

case "$OSTYPE" in
  linux*)
    alias ls='ls --color=auto'
    alias ll='ls -alF'
    alias la='ls -A'
    alias l='ls -CF'
    alias base64-decode='base64 -d'

    ;;
  darwin*)
    alias ls='ls -G'
    alias ll='ls -al'
    alias base64-decode='base64 -D'
    ;;
esac

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias watchit='watch --color -n 1 '
alias codediff='touch  /tmp/diff-file1 /tmp/diff-file2 && code -n --diff /tmp/diff-file1 /tmp/diff-file2'
alias opentodos='
  cd $HOME/drive/notes/todo-txt &&
  vim \
    todo.txt \
    routines.todo.txt \
    projects.todo.txt \
    someday.todo.txt
  '

# So I don't need to remember the options to tar every time
alias untar='tar xzvf'
alias tarup='tar czvf'
alias git-pick-branch='git branch | fzf | sed '\''s+remotes/origin/++g'\'' | xargs git checkout'
