#!/usr/bin/env bash
# Alias definitions.

case "${__DOTFILES_OS_PLATFORM}" in
  ubuntu)
    alias fopen='xdg-open'

    alias tcopy='xclip -selection clipboard'
    alias tpaste='xclip -selection clipboard -o'

    todotxt_executable="todo-txt"
    ;;

  wsl-ubuntu)
    alias fopen='start'

    alias tcopy='clip.exe'

    todotxt_executable="todo-txt"
    ;;

  macos)
    alias fopen='open'

    alias tcopy='pbcopy'
    alias tpaste='pbpaste'

    todotxt_executable="todo.sh"
    ;;
esac

alias todo="${todotxt_executable}"
alias todoadd="${todotxt_executable} -t add"
alias tododo="${todotxt_executable} -a do"
alias todoxp="${todotxt_executable} xp -o 10"

case "$OSTYPE" in
  linux*)
    alias ls='ls --color=auto'
    alias ll='ls -alF'
    alias la='ls -A'
    alias l='ls -CF'
    alias base64-decode='base64 -d'

    ;;
  darwin*)
    alias ls='ls -G'
    alias ll='ls -al'
    alias base64-decode='base64 -D'
    ;;
esac

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias watchit='watch --color -n 1 '
alias codediff='touch  /tmp/diff-file1 /tmp/diff-file2 && code -n --diff /tmp/diff-file1 /tmp/diff-file2'
