#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

readonly DOTFILES_HOME="${HOME}/dotfiles"
readonly DOTFILES_CONFIG="${DOTFILES_HOME}/config"

# shellcheck source=../lib/functions.bash
source "${DOTFILES_HOME}/lib/functions.bash"


set +e
command -v brew >/dev/null 2>&1
brew_installed=$?
set -e

if [[ ${brew_installed} -eq 0 ]] ; then
  util::info_message "homebrew is already installed"
else
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  source "${HOME}/.bashrc"
fi

platform="$(util::detect_platform)"

case "${platform}" in
  ubuntu)
    default_homebrew_packages=(
      gcc
      shfmt
      kubie
      k9s
      markdownlint-cli
    )
    ;;
  wsl-ubuntu)
    default_homebrew_packages=(
      gcc
      shfmt
      markdownlint-cli
    )
    ;;
  fedora)
    default_homebrew_packages=(
      shfmt
      todo-txt
      markdownlint-cli
    )
    ;;
  macos)
    default_homebrew_packages=(
      bash-completion@2
      gcc
      shfmt
      vim
      wget
      curl
      todo-txt
      k9s
      kubie
      pyenv
      tfenv
      the_silver_searcher
      htop
      shellcheck
      markdownlint-cli
      yq
      jq
    )
    ;;
esac

if [[ -n $* ]]; then
  homebrew_packages=("$@")
else
  homebrew_packages=("${default_homebrew_packages[@]}")
fi

homebrew_packages_sring=$(printf "%s " "${homebrew_packages[@]}")
util::info_message "Installing packages: ${homebrew_packages_sring}"

if ((${SET_DEBUG:-0})); then
  brew update
  brew install "${homebrew_packages[@]}"
else
  brew update >/dev/null 2>&1
  brew install -q "${homebrew_packages[@]}" >/dev/null 2>&1
fi

# util::info_message "Reinstall vim."
# # brew remove vim
# brew cleanup
# brew install vim --with-python

util::info_message "Packages installed."
