#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

readonly DOTFILES_HOME="${HOME}/dotfiles"
readonly DOTFILES_CONFIG="${DOTFILES_HOME}/config"

# shellcheck source=lib/functions.bash
source "${DOTFILES_HOME}/lib/functions.bash"

platform="$(util::detect_platform)"

case "${platform}" in
  ubuntu)
    curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash
    bash scripts/dotfiles-install-ubuntu-apt-packages vim-gtk nodejs shellcheck
    ;;
  wsl-ubuntu)
    curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash
    bash scripts/dotfiles-install-ubuntu-apt-packages vim-gtk nodejs shellcheck
    ;;
  fedora)
    bash scripts/dotfiles-install-fedora-dnf-packages nodejs vim-enhanced vim-X11 ShellCheck
    ;;
  macos)
    bash scripts/dotfiles-install-homebrew-packages node@22
    brew link node@22
    ;;
esac

bash scripts/dotfiles-link-dotfile "${DOTFILES_CONFIG}/vimrc" "${HOME}/.vimrc"

if [[ ! -f "$HOME/.vim/autoload/plug.vim" ]]; then
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

  vim +PlugInstall +qall
fi

# vim +PlugUpdate +qall
# vim +PlugClean +qall

