#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

readonly DOTFILES_HOME="${HOME}/dotfiles"
readonly DOTFILES_CONFIG="${DOTFILES_HOME}/config"

# shellcheck source=lib/functions.bash
source "${DOTFILES_HOME}/lib/functions.bash"

platform="$(util::detect_platform)"

if [[ "${platform}" != ubuntu && "${platform}" != wsl-ubuntu ]]; then
  util::die "This script run only on Ubuntu"
fi

case "${platform}" in
  ubuntu)
    default_ubuntu_apt_packages=(
      curl
      wget
      git
      bash-completion
      htop
      todotxt-cli
      xsel
      xclip
      build-essential
      gcc
      file
      git
    )
    ;;
  wsl-ubuntu)
    default_ubuntu_apt_packages=(
      curl
      wget
      git
      bash-completion
      htop
      todotxt-cli
      build-essential
      gcc
      file
      git
    )
    ;;
  fedora)
    echo "Detected platform: fedora. Skip."
    ;;
  macos)
    echo "Detected platform: macos. Skip."
    ;;
esac

if [[ -n $* ]]; then
  ubuntu_apt_packages=("$@")
else
  ubuntu_apt_packages=("${default_ubuntu_apt_packages[@]}")
fi

ubuntu_apt_packages_string=$(printf "%s " "${ubuntu_apt_packages[@]}")
util::info_message "Installing apt packages: ${ubuntu_apt_packages_string}"
if ((${SET_DEBUG:-0})); then
  sudo apt update
  sudo apt install -y "${ubuntu_apt_packages[@]}"
else
  sudo apt update >/dev/null 2>&1
  sudo apt install -y "${ubuntu_apt_packages[@]}" >/dev/null 2>&1
fi

util::info_message "Packages installed."
