#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

desired_version="v0.10.0"
install_dir="/usr/local/bin"

if [[ "${OSTYPE}" == linux* ]]; then
  os_platform="linux"
elif [[ "${OSTYPE}" == darwin* ]]; then
  os_platform="darwin"
else
  echo "OS type ${OSTYPE} not supported by the script. Exiting."
  exit 1
fi

binary_url="https://kind.sigs.k8s.io/dl/${desired_version}/kind-${os_platform}-amd64"

curl -Lo ./kind ${binary_url}
chmod +x ./kind
sudo mv ./kind "${install_dir}/kind"

cat << EOF > "${HOME}/kind-config.yaml"
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: kindest/node:v1.18.15@sha256:5c1b980c4d0e0e8e7eb9f36f7df525d079a96169c8a8f20d8bd108c0d0889cc4
- role: worker
  image: kindest/node:v1.18.15@sha256:5c1b980c4d0e0e8e7eb9f36f7df525d079a96169c8a8f20d8bd108c0d0889cc4
- role: worker
  image: kindest/node:v1.18.15@sha256:5c1b980c4d0e0e8e7eb9f36f7df525d079a96169c8a8f20d8bd108c0d0889cc4
- role: worker
  image: kindest/node:v1.18.15@sha256:5c1b980c4d0e0e8e7eb9f36f7df525d079a96169c8a8f20d8bd108c0d0889cc4
EOF

echo "Usage:"
echo "Create cluster:"
echo kind create cluster \
  --kubeconfig ~/.kube/config \
  --config $HOME/kind-config.yaml \
  --wait 5m \
  --name local-cluster


echo "Delete cluster:"
echo "kind delete cluster --name local-cluster"

