#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

desired_version=${1:-v1.19.6}
install_dir="/usr/local/bin"


if [[ "${OSTYPE}" == linux* ]]; then
  os_platform="linux"
elif [[ "${OSTYPE}" == darwin* ]]; then
  os_platform="darwin"
else
  echo "OS type ${OSTYPE} not supported by the script. Exiting."
  exit 1
fi

binary_url="https://storage.googleapis.com/kubernetes-release/release/${desired_version}/bin/${os_platform}/amd64/kubectl"

sudo wget "${binary_url}" -O "${install_dir}/kubectl"
sudo chmod +x "${install_dir}/kubectl"

### Enable kubectl autocompletion by adding the the completion script
if type kubectl  > /dev/null 2>&1 ; then
  if [[ ! -z $BASH_COMPLETION_COMPAT_DIR ]]
    kubectl completion bash >${BASH_COMPLETION_COMPAT_DIR}/kubectl
  fi
fi
