#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

desired_version="v0.25.18"
install_dir="/usr/local/bin"

if [[ "${OSTYPE}" == linux* ]]; then
  os_platform="Linux"
  arch_string="x86_64"
elif [[ "${OSTYPE}" == darwin* ]]; then
  os_platform="Darwin"
  arch_string="x86_64"
else
  echo "OS type ${OSTYPE} not supported by the script. Exiting."
  exit 1
fi

tar_file_name="k9s_${os_platform}_${arch_string}.tar.gz"
binary_url="https://github.com/derailed/k9s/releases/download/${desired_version}/${tar_file_name}"

wget ${binary_url}
tar -xf "${tar_file_name}"
rm -f "${tar_file_name}"
chmod +x k9s
sudo mv ./k9s "${install_dir}/k9s"
