#!/usr/bin/env bash

# Strict Mode - http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

temp_dir_path="/tmp/kind-local-multi-node-kind-cluster"

kind_create_local_multi_node_kind_cluster() {
  kind create cluster \
    --kubeconfig ~/.kube/config \
    --config $HOME/dotfiles/config/k8s/local-multi-node-kind-cluster.yaml \
    --wait 5m \
    --name local-multi-node-kind-cluster

  kubectl cluster-info --context kind-local-multi-node-kind-cluster \
    --kubeconfig ~/.kube/config

}

install_metric_server() {
# Ref: https://gist.github.com/sanketsudake/a089e691286bf2189bfedf295222bd43

  kubectl config use-context kind-local-multi-node-kind-cluster \
    --kubeconfig ~/.kube/config

  metric_server_temp_dir_path="${temp_dir_path}/metric-server-kustomize"
  if [ ! -d "${metric_server_temp_dir_path}" ]; then
    mkdir -p "${metric_server_temp_dir_path}"
  fi

  cat << EOF > "${metric_server_temp_dir_path}/kustomization.yml"
bases:
  - https://github.com/kubernetes-sigs/metrics-server/releases/download/v0.6.2/components.yaml

patchesJson6902:
  - target:
      version: v1
      kind: Deployment
      name: metrics-server
      namespace: kube-system
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --kubelet-insecure-tls
EOF

  kubectl apply -k "${metric_server_temp_dir_path}"

}

main() {
kind_create_local_multi_node_kind_cluster

if [ ! -d "${temp_dir_path}" ]; then
  mkdir -p "${temp_dir_path}"
fi
install_metric_server
}

main "$@"
